In [2]:
import numpy as np

In [4]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
print(np.where(a==6))

(array([1], dtype=int64), array([2], dtype=int64))


In [4]:
print(np.where(a%2==0))

(array([0, 0, 1, 1, 2, 2], dtype=int64), array([0, 2, 0, 2, 0, 2], dtype=int64))
