In [1]:
import numpy as np

In [2]:
# 1D array
a = np.array([1,2])
a

array([1, 2])

In [3]:
# 2d array
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [6]:
# best way to form arrays
a1 = np.arange(12).reshape(3,4)
a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])