In [1]:
import numpy as np

In [10]:
a = np.array([1,2])
b=np.arange(12).reshape(4,3)
a,b

(array([1, 2]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [11]:
# ndim
a.ndim,b.ndim

(1, 2)

In [6]:
# itemsize (size of the datatype for example int takes 4 bytes)
b.itemsize

4

In [14]:
# dtype
c= np.array([[1,4],[5,6]],dtype=complex)
c,c.dtype,c.itemsize

(array([[1.+0.j, 4.+0.j],
        [5.+0.j, 6.+0.j]]),
 dtype('complex128'),
 16)

In [12]:
# size (total elements)
b.size

12

In [15]:
# shape
b.shape,c.shape

((4, 3), (2, 2))

In [26]:
# reshape (we can put -1 for the unknown dimension)
x=np.arange(12).reshape(2,2,-1)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [27]:
x.shape

(2, 2, 3)

In [10]:
# zeroes
np.zeros((2,2),dtype=int),np.ones((2,2),dtype=int)



(array([[0, 0],
        [0, 0]]),
 array([[1, 1],
        [1, 1]]))

In [11]:
# any number
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [31]:
# random decimal numbers (this will give random decimals between 0 and 10)
(np.random.rand(3,4))*10

array([[8.79456906, 8.59889459, 8.77694277, 0.12270402],
       [0.92741752, 1.09785969, 8.56109963, 7.20820029],
       [9.91306402, 8.57865485, 4.32328394, 5.01128595]])

In [13]:
# random integer numbers
np.random.randint(2,8,size=(2,3))

array([[6, 4, 5],
       [5, 4, 4]])

In [14]:
# identity matrix
np.identity(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [40]:
# repeat arrray
r = np.array([[1,2,3]])
r1 = np.repeat(r , 3, axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [49]:
# exercise
e = np.ones((5,5),dtype=int)
e[1:4,1:4]=0
e[2,2]=9
e

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])