In [2]:
import numpy as np

In [3]:
# arange
a = np.arange(10)
b = np.arange(2,7)
c = np.arange(0,6,2)
a,b,c

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([2, 3, 4, 5, 6]),
 array([0, 2, 4]))

In [4]:
# linspace (inserts equal space numbers in given range)
a1=np.linspace(1,5,10)
a1

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [5]:

b1 = np.arange(12).reshape(3,4)
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
# ravel (can use flatten() also)
b1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
# min,max
b1.min(),b1.max()

(0, 11)

In [8]:

b = np.arange(6).reshape(3,2)
c = np.arange(6,12).reshape(3,2)
b,c

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]))

In [9]:
# stacking (horizontal)
np.hstack((b,c))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [10]:
# stacking (vertical)
np.vstack((b,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [11]:
a = np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [12]:
# split (horizontal)
np.hsplit(a,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [13]:
# split (vertical)

np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [15]:
# to copy
a = np.array([1,2,3])
b = a.copy()
b[0]=56
b,a

(array([56,  2,  3]), array([1, 2, 3]))