In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [3]:
# sum operations (axis = 0 - adds columns values
#                 axis = 1 - adds rows values)
a.sum(),a.sum(axis=0),a.sum(axis=1)

(66, array([18, 22, 26]), array([ 3, 12, 21, 30]))

In [4]:
# sqrt
np.sqrt(a)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [5]:
# standard deviation
np.std(a)

3.452052529534663

In [7]:
b = np.arange(1,5).reshape(2,2)
c = np.arange(5,9).reshape(2,2)
b,c

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [11]:
# basic operations
b+c,c-b,c*b,b/c

(array([[ 6,  8],
        [10, 12]]),
 array([[4, 4],
        [4, 4]]),
 array([[ 5, 12],
        [21, 32]]),
 array([[0.2       , 0.33333333],
        [0.42857143, 0.5       ]]),
 array([[ 5, 12],
        [21, 32]]))

In [12]:
# matrix product
np.dot(b,c)

array([[19, 22],
       [43, 50]])