In [1]:
import numpy as np


In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
# print 6 
a[1,2]

6

In [4]:
# print 10,11
a[2,2:4]

array([10, 11])

In [5]:
# print 5,9
a[1:3,1]

array([5, 9])

In [6]:
a[-1]

array([ 8,  9, 10, 11])

In [7]:
a[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])