In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
# basic iterate
for row in a:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


In [4]:
# flat
for cell in a.flat:
  print(cell)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [5]:

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

##### **NDITER**

In [6]:
# column wise (C order)
for x in np.nditer(a,order='C'):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [7]:
# row wise (Forton order)
for x in np.nditer(a,order='F'):
  print(x)
  

0
5
10
1
6
11
2
7
12
3
8
13
4
9
14


In [8]:
# print entire column
for x in np.nditer(a,order='F',flags=['external_loop']):
  print(x)

[ 0  5 10]
[ 1  6 11]
[ 2  7 12]
[ 3  8 13]
[ 4  9 14]


In [9]:
# MODIFY ARRAY
for x in np.nditer(a,op_flags=['readwrite']):
  x[...]=x + 5

a

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

NDENUMERATE


In [11]:
# ndenumerate example
a = np.array([[1,2],[3,4]])
for idx,x in np.ndenumerate(a):
  print(idx,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
