In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
# returns bool
b = a>6
b

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [4]:
# returns values that are true
a[b]

array([ 7,  8,  9, 10, 11])

In [5]:
# replacing values which are true
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, -1],
       [-1, -1, -1, -1]])