In [1]:
import numpy as np

CONCATENATE

In [2]:
# concatenate function
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


USING STACK FUNCTIONS

In [3]:
# horizontal stack 
x = np.hstack((arr1,arr2))
x

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [4]:
# vertical stack
y = np.vstack((arr1,arr2))
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
arr1,arr2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [6]:
# depth stack
z = np.dstack((arr1,arr2))
z

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])